### ISSUE TITLE
Expand create_short_unit function

### ISSUE THREAD

**Issue by spoonerf** [owid/importers#7]
Just a reminder to expand [create_short_unit()](https://github.com/owid/owid-importer/blob/4341713d7fa88b41327ea48419ed5785b5cb9faf/importer/utils.py#L45-L67) and to add it to this repo, perhaps to the [standard importer](https://github.com/owid/importers/tree/master/standard_importer) folder.

**Comment by edomt** [comment]
(Voluntarily leaving this issue here, since it's directly related to the code in this repo.)

**Comment by pabloarosado** [comment]
Hi @spoonerf, I just saw this issue, is it still relevant, or should we close it?

**Comment by spoonerf** [comment]
Ah yes I think it's redundant now - will close it!
